using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Azure.Functions.Worker;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace AzureFunctionDataverseEvents
{
    public class Function1
    {
        private readonly ILogger<Function1> _logger;

        public Function1(ILogger<Function1> logger)
        {
            _logger = logger;
        }

        [Function("Function1")]
        public async Task<IActionResult> RunAsync([HttpTrigger(AuthorizationLevel.Function, "get", "post")] HttpRequest req)
        {
            //_logger.LogInformation("C# HTTP trigger function processed a request.");
            //return new OkObjectResult("Welcome to Azure Functions!");

            _logger.LogInformation("C# HTTP trigger function processed a request.");

            string queryParams = "";
            foreach (var q in req.Query)
            {
                queryParams += $"Key: {q.Key} Value: {q.Value}\n";
            }

            string requestBody = await new StreamReader(req.Body).ReadToEndAsync();

            dynamic? data = JsonConvert.DeserializeObject(requestBody);
            if (data == null)
            {
                return new BadRequestObjectResult("Request body is invalid or empty.");
            }

            string requestHeader = "";
            foreach (var h in req.Headers)
            {
                requestHeader += $"Key: {h.Key} Value: {h.Value}\n";
            }
            _logger.LogInformation("Query Parameters:\n" + queryParams);
            _logger.LogInformation("Request Header: \n" + requestHeader);
            _logger.LogInformation("Request Body:\n" + requestBody);
            string requestBodyFormatted = JValue.Parse(requestBody).ToString(Formatting.Indented);
            _logger.LogInformation("Request Body Formatted:\n" + requestBodyFormatted);

            try
            {
                dynamic target = data.InputParameters["Target"];

                foreach (dynamic field in target.Attributes)
                {
                    _logger.LogInformation($"Name: {field.Key} Value: {field.Value}");
                }
            }
            catch (Exception ex)
            {
                _logger.LogInformation(ex.ToString());
            }

            return (ActionResult)new OkObjectResult(data.InitiatingUserId);
        }
    }

    // NOTE: The following code is commented out because it is the default template code generated by Visual Studio for an Azure Function for .NET Core 3.1. It has been replaced by the new implementation above.
    //public static class Function1
    //{
    //    [FunctionName("Function1")]
    //    public static async Task<IActionResult> Run(
    //        [HttpTrigger(AuthorizationLevel.Function, "get", "post", Route = null)] HttpRequest req,
    //        ILogger log)
    //    {
    //        log.LogInformation("C# HTTP trigger function processed a request.");

    //        string name = req.Query["name"];

    //        string requestBody = await new StreamReader(req.Body).ReadToEndAsync();
    //        dynamic data = JsonConvert.DeserializeObject(requestBody);
    //        name = name ?? data?.name;

    //        string responseMessage = string.IsNullOrEmpty(name)
    //            ? "This HTTP triggered function executed successfully. Pass a name in the query string or in the request body for a personalized response."
    //            : $"Hello, {name}. This HTTP triggered function executed successfully.";

    //        return new OkObjectResult(responseMessage);
    //    }
    //}
}
